/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as DashboardPanelRouteImport } from './routes/dashboard/_panel'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as DashboardPanelWalletRouteImport } from './routes/dashboard/_panel.wallet'
import { Route as DashboardPanelUsersRouteImport } from './routes/dashboard/_panel.users'
import { Route as DashboardPanelTicketsRouteImport } from './routes/dashboard/_panel.tickets'
import { Route as DashboardPanelStatsRouteImport } from './routes/dashboard/_panel.stats'
import { Route as DashboardPanelSettingsRouteImport } from './routes/dashboard/_panel.settings'
import { Route as DashboardPanelProfileRouteImport } from './routes/dashboard/_panel.profile'
import { Route as DashboardPanelMyEnrollmentsRouteImport } from './routes/dashboard/_panel.my-enrollments'
import { Route as DashboardPanelMyCoursesRouteImport } from './routes/dashboard/_panel.my-courses'
import { Route as DashboardPanelCreateCourseRouteImport } from './routes/dashboard/_panel.create-course'
import { Route as DashboardPanelBecomeInstructorRouteImport } from './routes/dashboard/_panel.become-instructor'
import { Route as DashboardPanelAuditLogRouteImport } from './routes/dashboard/_panel.audit-log'
import { Route as DashboardPanelSectionRouteImport } from './routes/dashboard/_panel.$section'
import { Route as ApiSetupRunMigrationsRouteImport } from './routes/api/setup/run-migrations'
import { Route as ApiAuthVerifyOtpRouteImport } from './routes/api/auth/verify-otp'
import { Route as ApiAuthVerifyEmailOtpRouteImport } from './routes/api/auth/verify-email-otp'
import { Route as ApiAuthRequestOtpRouteImport } from './routes/api/auth/request-otp'
import { Route as ApiAuthRequestEmailOtpRouteImport } from './routes/api/auth/request-email-otp'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as DashboardPanelTicketTicketIdRouteImport } from './routes/dashboard/_panel.ticket.$ticketId'
import { Route as DashboardPanelSupportTicketsRouteImport } from './routes/dashboard/_panel.support.tickets'
import { Route as DashboardPanelSupportPaymentsRouteImport } from './routes/dashboard/_panel.support.payments'
import { Route as DashboardPanelSupportManualEnrollmentRouteImport } from './routes/dashboard/_panel.support.manual-enrollment'
import { Route as DashboardPanelSupportInstructorApplicationsRouteImport } from './routes/dashboard/_panel.support.instructor-applications'
import { Route as DashboardPanelSupportCoursesRouteImport } from './routes/dashboard/_panel.support.courses'
import { Route as DashboardPanelEnrollCourseIdRouteImport } from './routes/dashboard/_panel.enroll.$courseId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPanelRoute = DashboardPanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPanelWalletRoute = DashboardPanelWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardPanelRoute,
} as any)
const DashboardPanelUsersRoute = DashboardPanelUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardPanelRoute,
} as any)
const DashboardPanelTicketsRoute = DashboardPanelTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardPanelRoute,
} as any)
const DashboardPanelStatsRoute = DashboardPanelStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardPanelRoute,
} as any)
const DashboardPanelSettingsRoute = DashboardPanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardPanelRoute,
} as any)
const DashboardPanelProfileRoute = DashboardPanelProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardPanelRoute,
} as any)
const DashboardPanelMyEnrollmentsRoute =
  DashboardPanelMyEnrollmentsRouteImport.update({
    id: '/my-enrollments',
    path: '/my-enrollments',
    getParentRoute: () => DashboardPanelRoute,
  } as any)
const DashboardPanelMyCoursesRoute = DashboardPanelMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => DashboardPanelRoute,
} as any)
const DashboardPanelCreateCourseRoute =
  DashboardPanelCreateCourseRouteImport.update({
    id: '/create-course',
    path: '/create-course',
    getParentRoute: () => DashboardPanelRoute,
  } as any)
const DashboardPanelBecomeInstructorRoute =
  DashboardPanelBecomeInstructorRouteImport.update({
    id: '/become-instructor',
    path: '/become-instructor',
    getParentRoute: () => DashboardPanelRoute,
  } as any)
const DashboardPanelAuditLogRoute = DashboardPanelAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardPanelRoute,
} as any)
const DashboardPanelSectionRoute = DashboardPanelSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DashboardPanelRoute,
} as any)
const ApiSetupRunMigrationsRoute = ApiSetupRunMigrationsRouteImport.update({
  id: '/api/setup/run-migrations',
  path: '/api/setup/run-migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyOtpRoute = ApiAuthVerifyOtpRouteImport.update({
  id: '/api/auth/verify-otp',
  path: '/api/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyEmailOtpRoute = ApiAuthVerifyEmailOtpRouteImport.update({
  id: '/api/auth/verify-email-otp',
  path: '/api/auth/verify-email-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRequestOtpRoute = ApiAuthRequestOtpRouteImport.update({
  id: '/api/auth/request-otp',
  path: '/api/auth/request-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRequestEmailOtpRoute = ApiAuthRequestEmailOtpRouteImport.update({
  id: '/api/auth/request-email-otp',
  path: '/api/auth/request-email-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPanelTicketTicketIdRoute =
  DashboardPanelTicketTicketIdRouteImport.update({
    id: '/ticket/$ticketId',
    path: '/ticket/$ticketId',
    getParentRoute: () => DashboardPanelRoute,
  } as any)
const DashboardPanelSupportTicketsRoute =
  DashboardPanelSupportTicketsRouteImport.update({
    id: '/support/tickets',
    path: '/support/tickets',
    getParentRoute: () => DashboardPanelRoute,
  } as any)
const DashboardPanelSupportPaymentsRoute =
  DashboardPanelSupportPaymentsRouteImport.update({
    id: '/support/payments',
    path: '/support/payments',
    getParentRoute: () => DashboardPanelRoute,
  } as any)
const DashboardPanelSupportManualEnrollmentRoute =
  DashboardPanelSupportManualEnrollmentRouteImport.update({
    id: '/support/manual-enrollment',
    path: '/support/manual-enrollment',
    getParentRoute: () => DashboardPanelRoute,
  } as any)
const DashboardPanelSupportInstructorApplicationsRoute =
  DashboardPanelSupportInstructorApplicationsRouteImport.update({
    id: '/support/instructor-applications',
    path: '/support/instructor-applications',
    getParentRoute: () => DashboardPanelRoute,
  } as any)
const DashboardPanelSupportCoursesRoute =
  DashboardPanelSupportCoursesRouteImport.update({
    id: '/support/courses',
    path: '/support/courses',
    getParentRoute: () => DashboardPanelRoute,
  } as any)
const DashboardPanelEnrollCourseIdRoute =
  DashboardPanelEnrollCourseIdRouteImport.update({
    id: '/enroll/$courseId',
    path: '/enroll/$courseId',
    getParentRoute: () => DashboardPanelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/request-email-otp': typeof ApiAuthRequestEmailOtpRoute
  '/api/auth/request-otp': typeof ApiAuthRequestOtpRoute
  '/api/auth/verify-email-otp': typeof ApiAuthVerifyEmailOtpRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/api/setup/run-migrations': typeof ApiSetupRunMigrationsRoute
  '/dashboard/$section': typeof DashboardPanelSectionRoute
  '/dashboard/audit-log': typeof DashboardPanelAuditLogRoute
  '/dashboard/become-instructor': typeof DashboardPanelBecomeInstructorRoute
  '/dashboard/create-course': typeof DashboardPanelCreateCourseRoute
  '/dashboard/my-courses': typeof DashboardPanelMyCoursesRoute
  '/dashboard/my-enrollments': typeof DashboardPanelMyEnrollmentsRoute
  '/dashboard/profile': typeof DashboardPanelProfileRoute
  '/dashboard/settings': typeof DashboardPanelSettingsRoute
  '/dashboard/stats': typeof DashboardPanelStatsRoute
  '/dashboard/tickets': typeof DashboardPanelTicketsRoute
  '/dashboard/users': typeof DashboardPanelUsersRoute
  '/dashboard/wallet': typeof DashboardPanelWalletRoute
  '/dashboard/enroll/$courseId': typeof DashboardPanelEnrollCourseIdRoute
  '/dashboard/support/courses': typeof DashboardPanelSupportCoursesRoute
  '/dashboard/support/instructor-applications': typeof DashboardPanelSupportInstructorApplicationsRoute
  '/dashboard/support/manual-enrollment': typeof DashboardPanelSupportManualEnrollmentRoute
  '/dashboard/support/payments': typeof DashboardPanelSupportPaymentsRoute
  '/dashboard/support/tickets': typeof DashboardPanelSupportTicketsRoute
  '/dashboard/ticket/$ticketId': typeof DashboardPanelTicketTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/request-email-otp': typeof ApiAuthRequestEmailOtpRoute
  '/api/auth/request-otp': typeof ApiAuthRequestOtpRoute
  '/api/auth/verify-email-otp': typeof ApiAuthVerifyEmailOtpRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/api/setup/run-migrations': typeof ApiSetupRunMigrationsRoute
  '/dashboard/$section': typeof DashboardPanelSectionRoute
  '/dashboard/audit-log': typeof DashboardPanelAuditLogRoute
  '/dashboard/become-instructor': typeof DashboardPanelBecomeInstructorRoute
  '/dashboard/create-course': typeof DashboardPanelCreateCourseRoute
  '/dashboard/my-courses': typeof DashboardPanelMyCoursesRoute
  '/dashboard/my-enrollments': typeof DashboardPanelMyEnrollmentsRoute
  '/dashboard/profile': typeof DashboardPanelProfileRoute
  '/dashboard/settings': typeof DashboardPanelSettingsRoute
  '/dashboard/stats': typeof DashboardPanelStatsRoute
  '/dashboard/tickets': typeof DashboardPanelTicketsRoute
  '/dashboard/users': typeof DashboardPanelUsersRoute
  '/dashboard/wallet': typeof DashboardPanelWalletRoute
  '/dashboard/enroll/$courseId': typeof DashboardPanelEnrollCourseIdRoute
  '/dashboard/support/courses': typeof DashboardPanelSupportCoursesRoute
  '/dashboard/support/instructor-applications': typeof DashboardPanelSupportInstructorApplicationsRoute
  '/dashboard/support/manual-enrollment': typeof DashboardPanelSupportManualEnrollmentRoute
  '/dashboard/support/payments': typeof DashboardPanelSupportPaymentsRoute
  '/dashboard/support/tickets': typeof DashboardPanelSupportTicketsRoute
  '/dashboard/ticket/$ticketId': typeof DashboardPanelTicketTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/_panel': typeof DashboardPanelRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/request-email-otp': typeof ApiAuthRequestEmailOtpRoute
  '/api/auth/request-otp': typeof ApiAuthRequestOtpRoute
  '/api/auth/verify-email-otp': typeof ApiAuthVerifyEmailOtpRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/api/setup/run-migrations': typeof ApiSetupRunMigrationsRoute
  '/dashboard/_panel/$section': typeof DashboardPanelSectionRoute
  '/dashboard/_panel/audit-log': typeof DashboardPanelAuditLogRoute
  '/dashboard/_panel/become-instructor': typeof DashboardPanelBecomeInstructorRoute
  '/dashboard/_panel/create-course': typeof DashboardPanelCreateCourseRoute
  '/dashboard/_panel/my-courses': typeof DashboardPanelMyCoursesRoute
  '/dashboard/_panel/my-enrollments': typeof DashboardPanelMyEnrollmentsRoute
  '/dashboard/_panel/profile': typeof DashboardPanelProfileRoute
  '/dashboard/_panel/settings': typeof DashboardPanelSettingsRoute
  '/dashboard/_panel/stats': typeof DashboardPanelStatsRoute
  '/dashboard/_panel/tickets': typeof DashboardPanelTicketsRoute
  '/dashboard/_panel/users': typeof DashboardPanelUsersRoute
  '/dashboard/_panel/wallet': typeof DashboardPanelWalletRoute
  '/dashboard/_panel/enroll/$courseId': typeof DashboardPanelEnrollCourseIdRoute
  '/dashboard/_panel/support/courses': typeof DashboardPanelSupportCoursesRoute
  '/dashboard/_panel/support/instructor-applications': typeof DashboardPanelSupportInstructorApplicationsRoute
  '/dashboard/_panel/support/manual-enrollment': typeof DashboardPanelSupportManualEnrollmentRoute
  '/dashboard/_panel/support/payments': typeof DashboardPanelSupportPaymentsRoute
  '/dashboard/_panel/support/tickets': typeof DashboardPanelSupportTicketsRoute
  '/dashboard/_panel/ticket/$ticketId': typeof DashboardPanelTicketTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/faq'
    | '/sitemap.xml'
    | '/courses/$slug'
    | '/courses/'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/request-email-otp'
    | '/api/auth/request-otp'
    | '/api/auth/verify-email-otp'
    | '/api/auth/verify-otp'
    | '/api/setup/run-migrations'
    | '/dashboard/$section'
    | '/dashboard/audit-log'
    | '/dashboard/become-instructor'
    | '/dashboard/create-course'
    | '/dashboard/my-courses'
    | '/dashboard/my-enrollments'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/stats'
    | '/dashboard/tickets'
    | '/dashboard/users'
    | '/dashboard/wallet'
    | '/dashboard/enroll/$courseId'
    | '/dashboard/support/courses'
    | '/dashboard/support/instructor-applications'
    | '/dashboard/support/manual-enrollment'
    | '/dashboard/support/payments'
    | '/dashboard/support/tickets'
    | '/dashboard/ticket/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/faq'
    | '/sitemap.xml'
    | '/courses/$slug'
    | '/courses'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/request-email-otp'
    | '/api/auth/request-otp'
    | '/api/auth/verify-email-otp'
    | '/api/auth/verify-otp'
    | '/api/setup/run-migrations'
    | '/dashboard/$section'
    | '/dashboard/audit-log'
    | '/dashboard/become-instructor'
    | '/dashboard/create-course'
    | '/dashboard/my-courses'
    | '/dashboard/my-enrollments'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/stats'
    | '/dashboard/tickets'
    | '/dashboard/users'
    | '/dashboard/wallet'
    | '/dashboard/enroll/$courseId'
    | '/dashboard/support/courses'
    | '/dashboard/support/instructor-applications'
    | '/dashboard/support/manual-enrollment'
    | '/dashboard/support/payments'
    | '/dashboard/support/tickets'
    | '/dashboard/ticket/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/faq'
    | '/sitemap.xml'
    | '/courses/$slug'
    | '/dashboard/_panel'
    | '/courses/'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/request-email-otp'
    | '/api/auth/request-otp'
    | '/api/auth/verify-email-otp'
    | '/api/auth/verify-otp'
    | '/api/setup/run-migrations'
    | '/dashboard/_panel/$section'
    | '/dashboard/_panel/audit-log'
    | '/dashboard/_panel/become-instructor'
    | '/dashboard/_panel/create-course'
    | '/dashboard/_panel/my-courses'
    | '/dashboard/_panel/my-enrollments'
    | '/dashboard/_panel/profile'
    | '/dashboard/_panel/settings'
    | '/dashboard/_panel/stats'
    | '/dashboard/_panel/tickets'
    | '/dashboard/_panel/users'
    | '/dashboard/_panel/wallet'
    | '/dashboard/_panel/enroll/$courseId'
    | '/dashboard/_panel/support/courses'
    | '/dashboard/_panel/support/instructor-applications'
    | '/dashboard/_panel/support/manual-enrollment'
    | '/dashboard/_panel/support/payments'
    | '/dashboard/_panel/support/tickets'
    | '/dashboard/_panel/ticket/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  FaqRoute: typeof FaqRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRequestEmailOtpRoute: typeof ApiAuthRequestEmailOtpRoute
  ApiAuthRequestOtpRoute: typeof ApiAuthRequestOtpRoute
  ApiAuthVerifyEmailOtpRoute: typeof ApiAuthVerifyEmailOtpRoute
  ApiAuthVerifyOtpRoute: typeof ApiAuthVerifyOtpRoute
  ApiSetupRunMigrationsRoute: typeof ApiSetupRunMigrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_panel': {
      id: '/dashboard/_panel'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardPanelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_panel/wallet': {
      id: '/dashboard/_panel/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardPanelWalletRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/users': {
      id: '/dashboard/_panel/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardPanelUsersRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/tickets': {
      id: '/dashboard/_panel/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardPanelTicketsRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/stats': {
      id: '/dashboard/_panel/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardPanelStatsRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/settings': {
      id: '/dashboard/_panel/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardPanelSettingsRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/profile': {
      id: '/dashboard/_panel/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardPanelProfileRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/my-enrollments': {
      id: '/dashboard/_panel/my-enrollments'
      path: '/my-enrollments'
      fullPath: '/dashboard/my-enrollments'
      preLoaderRoute: typeof DashboardPanelMyEnrollmentsRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/my-courses': {
      id: '/dashboard/_panel/my-courses'
      path: '/my-courses'
      fullPath: '/dashboard/my-courses'
      preLoaderRoute: typeof DashboardPanelMyCoursesRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/create-course': {
      id: '/dashboard/_panel/create-course'
      path: '/create-course'
      fullPath: '/dashboard/create-course'
      preLoaderRoute: typeof DashboardPanelCreateCourseRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/become-instructor': {
      id: '/dashboard/_panel/become-instructor'
      path: '/become-instructor'
      fullPath: '/dashboard/become-instructor'
      preLoaderRoute: typeof DashboardPanelBecomeInstructorRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/audit-log': {
      id: '/dashboard/_panel/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/audit-log'
      preLoaderRoute: typeof DashboardPanelAuditLogRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/$section': {
      id: '/dashboard/_panel/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardPanelSectionRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/api/setup/run-migrations': {
      id: '/api/setup/run-migrations'
      path: '/api/setup/run-migrations'
      fullPath: '/api/setup/run-migrations'
      preLoaderRoute: typeof ApiSetupRunMigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-otp': {
      id: '/api/auth/verify-otp'
      path: '/api/auth/verify-otp'
      fullPath: '/api/auth/verify-otp'
      preLoaderRoute: typeof ApiAuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-email-otp': {
      id: '/api/auth/verify-email-otp'
      path: '/api/auth/verify-email-otp'
      fullPath: '/api/auth/verify-email-otp'
      preLoaderRoute: typeof ApiAuthVerifyEmailOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request-otp': {
      id: '/api/auth/request-otp'
      path: '/api/auth/request-otp'
      fullPath: '/api/auth/request-otp'
      preLoaderRoute: typeof ApiAuthRequestOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request-email-otp': {
      id: '/api/auth/request-email-otp'
      path: '/api/auth/request-email-otp'
      fullPath: '/api/auth/request-email-otp'
      preLoaderRoute: typeof ApiAuthRequestEmailOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_panel/ticket/$ticketId': {
      id: '/dashboard/_panel/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/dashboard/ticket/$ticketId'
      preLoaderRoute: typeof DashboardPanelTicketTicketIdRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/support/tickets': {
      id: '/dashboard/_panel/support/tickets'
      path: '/support/tickets'
      fullPath: '/dashboard/support/tickets'
      preLoaderRoute: typeof DashboardPanelSupportTicketsRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/support/payments': {
      id: '/dashboard/_panel/support/payments'
      path: '/support/payments'
      fullPath: '/dashboard/support/payments'
      preLoaderRoute: typeof DashboardPanelSupportPaymentsRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/support/manual-enrollment': {
      id: '/dashboard/_panel/support/manual-enrollment'
      path: '/support/manual-enrollment'
      fullPath: '/dashboard/support/manual-enrollment'
      preLoaderRoute: typeof DashboardPanelSupportManualEnrollmentRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/support/instructor-applications': {
      id: '/dashboard/_panel/support/instructor-applications'
      path: '/support/instructor-applications'
      fullPath: '/dashboard/support/instructor-applications'
      preLoaderRoute: typeof DashboardPanelSupportInstructorApplicationsRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/support/courses': {
      id: '/dashboard/_panel/support/courses'
      path: '/support/courses'
      fullPath: '/dashboard/support/courses'
      preLoaderRoute: typeof DashboardPanelSupportCoursesRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
    '/dashboard/_panel/enroll/$courseId': {
      id: '/dashboard/_panel/enroll/$courseId'
      path: '/enroll/$courseId'
      fullPath: '/dashboard/enroll/$courseId'
      preLoaderRoute: typeof DashboardPanelEnrollCourseIdRouteImport
      parentRoute: typeof DashboardPanelRoute
    }
  }
}

interface DashboardPanelRouteChildren {
  DashboardPanelSectionRoute: typeof DashboardPanelSectionRoute
  DashboardPanelAuditLogRoute: typeof DashboardPanelAuditLogRoute
  DashboardPanelBecomeInstructorRoute: typeof DashboardPanelBecomeInstructorRoute
  DashboardPanelCreateCourseRoute: typeof DashboardPanelCreateCourseRoute
  DashboardPanelMyCoursesRoute: typeof DashboardPanelMyCoursesRoute
  DashboardPanelMyEnrollmentsRoute: typeof DashboardPanelMyEnrollmentsRoute
  DashboardPanelProfileRoute: typeof DashboardPanelProfileRoute
  DashboardPanelSettingsRoute: typeof DashboardPanelSettingsRoute
  DashboardPanelStatsRoute: typeof DashboardPanelStatsRoute
  DashboardPanelTicketsRoute: typeof DashboardPanelTicketsRoute
  DashboardPanelUsersRoute: typeof DashboardPanelUsersRoute
  DashboardPanelWalletRoute: typeof DashboardPanelWalletRoute
  DashboardPanelEnrollCourseIdRoute: typeof DashboardPanelEnrollCourseIdRoute
  DashboardPanelSupportCoursesRoute: typeof DashboardPanelSupportCoursesRoute
  DashboardPanelSupportInstructorApplicationsRoute: typeof DashboardPanelSupportInstructorApplicationsRoute
  DashboardPanelSupportManualEnrollmentRoute: typeof DashboardPanelSupportManualEnrollmentRoute
  DashboardPanelSupportPaymentsRoute: typeof DashboardPanelSupportPaymentsRoute
  DashboardPanelSupportTicketsRoute: typeof DashboardPanelSupportTicketsRoute
  DashboardPanelTicketTicketIdRoute: typeof DashboardPanelTicketTicketIdRoute
}

const DashboardPanelRouteChildren: DashboardPanelRouteChildren = {
  DashboardPanelSectionRoute: DashboardPanelSectionRoute,
  DashboardPanelAuditLogRoute: DashboardPanelAuditLogRoute,
  DashboardPanelBecomeInstructorRoute: DashboardPanelBecomeInstructorRoute,
  DashboardPanelCreateCourseRoute: DashboardPanelCreateCourseRoute,
  DashboardPanelMyCoursesRoute: DashboardPanelMyCoursesRoute,
  DashboardPanelMyEnrollmentsRoute: DashboardPanelMyEnrollmentsRoute,
  DashboardPanelProfileRoute: DashboardPanelProfileRoute,
  DashboardPanelSettingsRoute: DashboardPanelSettingsRoute,
  DashboardPanelStatsRoute: DashboardPanelStatsRoute,
  DashboardPanelTicketsRoute: DashboardPanelTicketsRoute,
  DashboardPanelUsersRoute: DashboardPanelUsersRoute,
  DashboardPanelWalletRoute: DashboardPanelWalletRoute,
  DashboardPanelEnrollCourseIdRoute: DashboardPanelEnrollCourseIdRoute,
  DashboardPanelSupportCoursesRoute: DashboardPanelSupportCoursesRoute,
  DashboardPanelSupportInstructorApplicationsRoute:
    DashboardPanelSupportInstructorApplicationsRoute,
  DashboardPanelSupportManualEnrollmentRoute:
    DashboardPanelSupportManualEnrollmentRoute,
  DashboardPanelSupportPaymentsRoute: DashboardPanelSupportPaymentsRoute,
  DashboardPanelSupportTicketsRoute: DashboardPanelSupportTicketsRoute,
  DashboardPanelTicketTicketIdRoute: DashboardPanelTicketTicketIdRoute,
}

const DashboardPanelRouteWithChildren = DashboardPanelRoute._addFileChildren(
  DashboardPanelRouteChildren,
)

interface DashboardRouteChildren {
  DashboardPanelRoute: typeof DashboardPanelRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPanelRoute: DashboardPanelRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  FaqRoute: FaqRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRequestEmailOtpRoute: ApiAuthRequestEmailOtpRoute,
  ApiAuthRequestOtpRoute: ApiAuthRequestOtpRoute,
  ApiAuthVerifyEmailOtpRoute: ApiAuthVerifyEmailOtpRoute,
  ApiAuthVerifyOtpRoute: ApiAuthVerifyOtpRoute,
  ApiSetupRunMigrationsRoute: ApiSetupRunMigrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
